// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "architecture/adr-0001.mdx": () => import("../content/docs/architecture/adr-0001.mdx?collection=docs"), "architecture/fiction-architecture-a.mdx": () => import("../content/docs/architecture/fiction-architecture-a.mdx?collection=docs"), "architecture/fiction-architecture-b.mdx": () => import("../content/docs/architecture/fiction-architecture-b.mdx?collection=docs"), "architecture/index.mdx": () => import("../content/docs/architecture/index.mdx?collection=docs"), "architecture/overview.mdx": () => import("../content/docs/architecture/overview.mdx?collection=docs"), "blueprints/fiction-blueprint-a.mdx": () => import("../content/docs/blueprints/fiction-blueprint-a.mdx?collection=docs"), "blueprints/fiction-blueprint-b.mdx": () => import("../content/docs/blueprints/fiction-blueprint-b.mdx?collection=docs"), "blueprints/index.mdx": () => import("../content/docs/blueprints/index.mdx?collection=docs"), "blueprints/system-context.mdx": () => import("../content/docs/blueprints/system-context.mdx?collection=docs"), "how-to/editor-options.mdx": () => import("../content/docs/how-to/editor-options.mdx?collection=docs"), "how-to/index.mdx": () => import("../content/docs/how-to/index.mdx?collection=docs"), "how-to/markdown-mermaid-raw.mdx": () => import("../content/docs/how-to/markdown-mermaid-raw.mdx?collection=docs"), "how-to/save-and-badges.mdx": () => import("../content/docs/how-to/save-and-badges.mdx?collection=docs"), "patterns/cache-aside.mdx": () => import("../content/docs/patterns/cache-aside.mdx?collection=docs"), "patterns/fiction-pattern-a.mdx": () => import("../content/docs/patterns/fiction-pattern-a.mdx?collection=docs"), "patterns/fiction-pattern-b.mdx": () => import("../content/docs/patterns/fiction-pattern-b.mdx?collection=docs"), "patterns/index.mdx": () => import("../content/docs/patterns/index.mdx?collection=docs"), "procedures/fiction-procedure-a.mdx": () => import("../content/docs/procedures/fiction-procedure-a.mdx?collection=docs"), "procedures/fiction-procedure-b.mdx": () => import("../content/docs/procedures/fiction-procedure-b.mdx?collection=docs"), "procedures/index.mdx": () => import("../content/docs/procedures/index.mdx?collection=docs"), "procedures/release-runbook.mdx": () => import("../content/docs/procedures/release-runbook.mdx?collection=docs"), "diagrams/data-flow.mdx": () => import("../content/docs/diagrams/data-flow.mdx?collection=docs"), "diagrams/fiction-diagram-a.mdx": () => import("../content/docs/diagrams/fiction-diagram-a.mdx?collection=docs"), "diagrams/fiction-diagram-b.mdx": () => import("../content/docs/diagrams/fiction-diagram-b.mdx?collection=docs"), "diagrams/index.mdx": () => import("../content/docs/diagrams/index.mdx?collection=docs"), }),
};
export default browserCollections;